### PR TITLE
Create stale.yml

### PR DESCRIPTION
**Pull request by mbaitelman**
# Description

Adds stale.yml to start clearing out older tickets. 
## Check List

- [ ] All tests pass. See TESTING.md for details.
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable.

### CODE REVIEW

**Comment by mbaitelman** [comment]
This should label anything older than a year as stale and then close them a week later

**Comment by ramereth** [comment]
@mbaitelman can you please fix the `yamllint` issues?

**Comment by mbaitelman** [comment]
Going to finish getting this yamllinted and then it has to be moved to the correct folder (standardfiles/cookbook)

**Comment by mbaitelman** [comment]
Part of the problem is that the Github examples don't follow yamllint rules.
Working on getting them in sync.

**Comment by Xorima** [comment]
yamllint is written by python users, it will be a little more stricter than most, for example in ruby yaml doesn't output in yaml that yamllint agrees with ...

**Comment by mbaitelman** [comment]
Thanks @Xorima 
Interesting to see the different rules

**Comment by mbaitelman** [comment]
Created #42 to replace this.

**Pull request closed without merging**
