### PR TITLE
Add dokken to the standardfiles

### PR DESCRIPTION
**Pull request by damacus**
# Description

Add dokken to the standardfiles

### CODE REVIEW

**Comment by damacus** [comment]
@sous-chefs/maintainers does anyone think we shouldn't standardise our dokken config? I'm not aware of any cases where dokken shouldn't be on a repo or should have different config.

**Comment by detjensrobert** [comment]
`selinux` and `selinux_policy` are the only two I'm aware of that do not work in Dokken.

**Comment by ramereth** [comment]
Will this override any customization we currently have in cookbooks? Or does this only gets applied if it's missing?

**Comment by ramereth** [comment]
Also, many of the windows-only cookbooks do not use dokken

**Comment by damacus** [comment]
> Also, many of the windows-only cookbooks do not use dokken

Yeah and as such it'll be a no-op on them. But 90+% of our cookbooks are Linux and this saves us having to copy and paste from the Java cookbook every week 😆

**Comment by damacus** [comment]
> `selinux` and `selinux_policy` are the only two I'm aware of that do not work in Dokken.

Cool, and in that case, adding these files won't actually do anything to them. I'll just have them lieing around doing nothing.

**Comment by ramereth** [comment]
> > Will this override any customization we currently have in cookbooks? Or does this only gets applied if it's missing?
> 
> It should override it, but I don't see any places where dokken needs to be customized, it should just be dokken config, which should be the same everywhere.

The other thing to consider is that you'd add platforms that aren't needed/supported in some cases (i.e. Debian/Ubuntu specific cookbooks such as aptly, etc and RHEL with yum-epel..)

I see in slack I see you said:
> So we decided we didn’t like the dokken standard file

So should this be closed now?

If there was a way to just add a standard dokken _if it were missing_ when adopting cookbooks, that would be nice.

**Pull request closed without merging**
